server:
  port: 8080  # Gateway will run on port 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Route 1: Send /api/auth/* requests to auth-service on port 8081
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1  # Removes /api from the path
            
        # Route 2: Send /api/payment/* requests to payment-service on port 8082
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=1
            
        # Route 3: Send /api/token/* requests to token-service on port 8083
        - id: token-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/token/**
          filters:
            - StripPrefix=1

# Enable health check endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info